### ISSUE TITLE
SDL1: Implement SDL_LoadObject()

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#107]
SDL2.0.15
AmigaOS4 FE - all Updates - Enhancer 1.5

I get an error on starting a shared build of ScummVM where it complains about not being able to access shared engine plugins due to SDL_LoadObject() not implemented.

I don't know how feasible that is, so feel free to reject.

(On a -not so- related note, this wouldn't gain any momentum for me since the infamous libstdc++.so crash also hits the SDL1 shared build.)

**Comment by capehill** [comment]
It's probably not a big effort, especially if SDL2 implementation can be recycled. Just a small note that feature hasn't been tested very heavily: it can print some text using libc.so but that's about it.

**Comment by raziel-** [comment]
No problem, thank you for looking at it.
