### ISSUE TITLE
[SDL2] Create a Prefs Tool for SDL

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/SDL_old#117]
For the next release it would be nice to have a simple Reaction based graphical prefs tool for both SDL1 and SDL2, in order to let users to configure atleast certain parameters.

That new prefs could eventually let users to:

Choose if enabled or disabled VSYNC
Choose the renderer selection
Etc.

**Comment by capehill** [comment]
Done: https://github.com/AmigaPorts/SDL-2.0/blob/main/amiga-extra/prefs.c

SDL1 doesn't have hint system.
