### ISSUE TITLE
[SDL2]: Initial fullscreen not "active"

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#122]
Can be checked with SDL1 and 2 builds of residualvm.

The SDL1 version is effectively immediately usable after start, while the SDL2 version need a mouse click into the launcher to become usable.
e.g. the buttons change color when the mouse pointer hovers over it.
This does not work right away with SDL2.

Could be a similar problem as it was with #98

**Comment by capehill** [comment]
Cannot reproduce. When I move mouse pointer over buttons in either window or fullscreen mode, they "activate", or turn brighter. 

Please double-triple check that you are linking against the latest SDL2 lib. I don't have other ideas right now.

**Comment by raziel-** [comment]
Yep, does not happen anymore.

Seems i had reverted to SDL2.0.9 when i did the tests.
Thank you for your time
