### ISSUE TITLE
[SDL1]: Black window/screen on mode switch

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#123]
This is a problem in SDL1 (thus i´m not sure if it is of any importance or wished to be fixed, but for the sake of completeness i post it anyway).

Steps to reproduce:
1) Start residualvm
2) Run Grim Fandango
3) Press ESC to reach the game
4) Press F1 to bring up the menu (game is paused)
5) Press ALT+ENTER to switch modes
The window/screen will come up black and stay that way until one presses ESC (both fullscreen and window affected).
Since this happens only in SDL1 but not in SDL2 i doubt it´s a bug in residualvm.

Then again, using the demo both (SDL1 and 2) are suffering from a black screen/window, so it might still as well be a bug in the game.

Edit: Forgot to add, since the game is "paused" could it be that because there is no drawing going on the window/screen itself is not updated/drawn?
Would be logical since pressing ESC makes the game run and draw again...
So, maybe a simple "redraw the window/screen" on a mode switch would be sufficient?

**Comment by capehill** [comment]
I haven't tried it on yet but SDL cannot redraw the window on behalf of the application. That would require it to read the old pixels first and then somehow drawing them and it would be a guesswork anyway. 

Maybe there is some missing event trigger instead of.

**Comment by raziel-** [comment]
I am still waiting for confirmation or rejection from residualvm tracker/devs.

Will report back once i get one

**Comment by capehill** [comment]
I'm sorry I haven't had a chance to check this for some time. Any news / tips from ResidualVM folks?

**Comment by raziel-** [comment]
Not really.
Only one answer since...but nothing terminal or remotely helpful, i'm afraid:
https://github.com/residualvm/residualvm/issues/1389

quote
I guess the game data affects how this issue occurs, but it's something we could fix properly regardless of game version.
/quote

**Comment by capehill** [comment]
If ResidualVM is now merged with ScummVM, does this issue still happen on ScummVM side?

**Comment by raziel-** [comment]
:-(
I'm so far behind with everything...sorry.

Will check and report back when I'm back home (March)

**Comment by raziel-** [comment]
@capehill

Well, i can't test if the error is still there.
The SDL1 build refuses to switch modes once i'm in Grim Fandango, why is beyond me, it still works fine in SDL2 (but there the error doesn't happen).

One more oddity is (since i haven't tested the SDL1 build for a long time) a regression on mouse cursor speed.
While SDL2 is real-time, SDL1 seems to slow the mouse pointer down in some way.
It feels as if SDL2 is running HD while SDL1 is running SD

**Comment by raziel-** [comment]
I was told that support for alt+enter switching from/to window/fullscreen was dropped from SDL1.

So, no chance to get back trying to fix any underlying issue.

Closing
