### ISSUE TITLE
[SDL2] Update to SDL 2.0.12 ?

### ISSUE THREAD

**Issue by BeWorld2018** [AmigaPorts/SDL_old#131]
Hi

It's possible to update AmigaPort/SDL to 2.0.12 release
We working on MorphOS port actually.

Thanks you.

**Comment by MBeijer** [comment]
@BeWorld2018 We do update SDL2 continously to be on par with the latest, but @capehill has to make sure nothing breaks between versions so it takes a little time.

Would you mind contributing with your MorphOS changes to our repo so we can have all SDL development collected in one place?

Currently I am working on consolidating the SDL1.2 AmigaOS4, AmigaOS3, WarpOS, MorphOS and AROS sources into one repository so it would be easier to manage and push updates for everyone.

And it would be great if the SDL2 development would be consolidated to begin with, so the extra work wouldn't be needed at a later point! :)

The best way would be if you fork our repository and do periodical pull requests to make us up to date! 

AmigaPorts/AmigaDev is a joint venture to consolidate development across all Amiga platforms and make lives easier for all developers no matter which platform they prefer to work with. :)

**Comment by BeWorld2018** [comment]
ok

we working with fork AmigaPort/SDL : https://github.com/BSzili/SDL/tree/mos-sdl2

**Comment by BSzili** [comment]
Right now the MorphOS port is still work in progress, but I'm going to send a pull request once I'm done with everything.

**Comment by MBeijer** [comment]
Pull of upstream changes in #132 
Waiting for @capehill to respond

**Comment by BSzili** [comment]
It appears that the upstream SDL mirror is no longer updated, the last commit is from Feb 19, so we are not at SDL 2.0.12 yet. There's another mirror that's on par with the official mercurial repo:
https://github.com/spurious/SDL-mirror
I think we could merge the stable 2.0.12 branch:
https://github.com/spurious/SDL-mirror/tree/release-2.0.12

**Comment by MBeijer** [comment]
Unfortunately, merging in updates from that repository might require some
manual work. I've tried to contact the maintainer of the SDL-mirror we're
forked from to see if we can get that up and running again.

**Comment by BSzili** [comment]
Right, I forgot that the commit hashes are different between the two mirrors. Hopefully you will be able to get a hold of Yoplitein. His website appears to be down as well :(

**Comment by MBeijer** [comment]
@BeWorld2018 @BSzili seems like the mirror is up and running again #136

**Comment by MBeijer** [comment]
Latest changes pulled in! :) @BSzili @BeWorld2018
