### ISSUE TITLE
Files doesnt exist on original repository

### ISSUE THREAD

**Issue by BeWorld2018** [AmigaPorts/SDL_old#139]
Hi !

In this directory https://github.com/AmigaPorts/SDL/tree/master/src/render
There is 3 files that doesnt exist in https://hg.libsdl.org/SDL/file/293eb6ce40ed/src/render
SDL_yuv_mmx.c, SDL_yuv_mmx_c.h and mmx.h

Can you delete it ?
Thanks

BeWorld

**Comment by capehill** [comment]
Done, thanks!
