### ISSUE TITLE
[SDL2] Current HEAD is not stable

### ISSUE THREAD

**Issue by BSzili** [AmigaPorts/SDL_old#141]
The last upstream merge happened at an arbitrary point, and it turns out that they were in the middle of some video system changes that cause stability issues. I'm trying to create my own branch for MorphOS based on the last stable 2.0.12 commit 8241656684eb2ff45c1ce4ea987576b6a9d05111. This means even when the MOS port reaches a mature state I'd have to maintain a separate fork to be able to build stable libraries from. Could the future upstream merges happen at release commits?

**Comment by capehill** [comment]
It probably has to be done manually, then. I cannot see an option to lock to some specific commit using Github pull request. @MBeijer  any ideas?

Other issue is that for some reason we don't have the latest upstream tags so need to lookup those commits manually, when necessary. Having tags would ease the release branching. I can now see the tags on SDL-mirror upstream, perhaps they have been updated recently.

I will try to pull the latest from upstream to see whether the tags update now or not. EDIT: no, tags didn't update.

**Comment by BSzili** [comment]
I think you have to turn on tag fetching separately, but I'm not very familiar with GitHub's web interface. Similarly I only know how to merge at specific tags or commits via git, not the GitHub pull request.

**Comment by MBeijer** [comment]
I’ll have to do it manually. I’ll fix it ASAP

**Comment by MBeijer** [comment]
The tags have been synced.
to get your fork sorted:
```
git remote add amigaports https://github.com/AmigaPorts/SDL.git
git fetch --all
git push origin --tags
```
@BSzili
