### ISSUE TITLE
Eat The Whistle freeze at startup

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/SDL_old#143]
Don't know if because of latest changes in SDL1, but the old port (2005) of the soccer game "Eat The Whistle" freeze at startup on my machine (Sam440)

http://os4depot.net/?function=showfile&file=game/sport/eatthewhistle.lha

Probably as first test it will worth to recompile it with latest SDL

**Comment by capehill** [comment]
According to https://en.wikipedia.org/wiki/AmigaOS_4_version_history , shared objects were added in 2007. Thus, that game is not using SDL as a shared object.

Try increasing the stack and contacting the original author.

**Comment by capehill** [comment]
At quick look the latest ETW source use SDL2 so maybe worth for someone to port them.

**Comment by capehill** [comment]
I have tested ETW on WinUAE and X5000.

On WinUAE it starts without issues.

On X5000 there is a DSI due PCI_GamePort.driver. If I disable PCI on AmigaInput prefs, I can start ETW without issues also on X5000.

1. Do you start ETW on icon or shell?

2. Do you see something in serial?

3. Have you tried disabling PCI on AmigaInput?

**Comment by samo79** [comment]
No crash on Sam440, but just a system freeze at startup .. but yeah, point 3 seems to be the root :-)
Before running the game we need to unticked the PCI_GamePort.driver from AmigaInput .. in that way game finally start !

Thanks for the tip, definitively you can close the ticket as problem was never related to SDL.

P.S.
You probably quite busy already with much important things, however would be nice to try to recompile latest version of the game with latest SDL :-)

**Comment by capehill** [comment]
Great, have to check AmigaInput bugs if there is an open ticket for this already.

Please write a post on SDL2 thread and maybe somebody updates the ETW port.
