### ISSUE TITLE
Make RebelSDL work (was: clib2 support)

### ISSUE THREAD

**Issue by afalkenhahn** [AmigaPorts/SDL_old#145]
Several users have asked me to provide an AmigaOS 4 version of my RebelSDL plugin for Hollywood, see here: https://www.hollywood-mal.com/docs/html/rebelsdl/

However, this is currently not possible because SDL2 on AmigaOS 4 needs newlib whereas Hollywood uses clib2. All attempts to make Hollywood handle newlib based plugins have failed so far, see here: https://forum.hyperion-entertainment.com/viewtopic.php?f=26&t=3743 

So it would be nice if there was a clib2 version of SDL2 for OS4 as well. Then I could support it in RebelSDL which would make it available to many Hollywood users.

**Comment by capehill** [comment]
I tried again your example since pthreads usage was removed some time ago, and added newlib.library opening to SDL2 because there was a newlib-related crash and then your (original?) example worked. Could you try it: http://capehill.kapsi.fi/sdl2/SDL2_ELF_test.lha

If you still need the clib2 version, it maybe possible but SDL needs threading support to be useful so thread-safe clib2 variant is required and it's unclear to me how to use / install it.

**Comment by afalkenhahn** [comment]
Sorry for the delay, I was very busy with other things. Now I've had some time to look at this again and what can I say: libSDL2-2.0.so from the archive you posted works very nicely now with my plugin! That is great, now I can finally release RebelSDL for OS4 too! Is this libSDL2-2.0.so publicly available somewhere or is it a beta build?

**Comment by capehill** [comment]
> 
> 
> Sorry for the delay, I was very busy with other things. Now I've had some time to look at this again and what can I say: libSDL2-2.0.so from the archive you posted works very nicely now with my plugin! That is great, now I can finally release RebelSDL for OS4 too! Is this libSDL2-2.0.so publicly available somewhere or is it a beta build?

Not yet, I will try to create a new 2.0.12 release candidate and hopefully that becomes the next release.

**Comment by afalkenhahn** [comment]
Ok, great. As soon as this is publicly available I'll release RebelSDL for OS4.

**Comment by capehill** [comment]
2.0.12 RC2 is up: https://github.com/AmigaPorts/SDL/releases/tag/v2.0.12-rc2-amigaos4

@kas1e @raziel- @softwarefailure if possible, please test it one more time before OS4Depot release.

**Comment by afalkenhahn** [comment]
Works nicely here!

**Comment by afalkenhahn** [comment]
Oh, wait, I found an issue but I won't have time to debug it today. I'll report back on it tomorrow so you might want to postpone the upload to OS4depot.net.

**Comment by raziel-** [comment]
@capehill 

Sorry, I'm at work for the coming 14 days where I won't be able to test.

If the bug @softwarefailure found will take longer to debug I'd appreciate it ;-)
Otherwise I guess you just release it and I'll put up bugs to the tracker later, if there'll be any...

**Comment by afalkenhahn** [comment]
Here's my report about the issue I was talking about yesterday: https://github.com/AmigaPorts/SDL/issues/149

**Comment by capehill** [comment]
I renamed this for closing. We will check the need for actual clib2 support in the future.
