### ISSUE TITLE
Pressing PrtScr shows "SysReq" as result

### ISSUE THREAD

**Issue by javierdlr** [AmigaPorts/SDL_old#147]
using checkeys from SDL2 test, when I press PrtScr key I get as result SysReq (is on same key, but should be trigger when holding AltGr/Shift/CantRemeberNow).

**Comment by javierdlr** [comment]
checkkeys shows correctly PrtScr now.

Tested with ZGloom, and seems not working (SDLK_PRINTSCREEN), maybe you only changed
SDL_SCANCODE#? and not SDLK_#? (or ZGloom uses a "dirty" not user-friendly way)
...
			if ((sEvent.type == SDL_KEYDOWN) && sEvent.key.keysym.sym == SDLK_SYSREQ)//SDLK_PRINTSCREEN)
			{
				printscreen = true;
			}
...

**Comment by capehill** [comment]
Works here with checkkeys and custom example. Are you 100% sure you are using the same SDL2 lib with checkkeys and ZGloom?

**Comment by capehill** [comment]
Any news?

**Comment by javierdlr** [comment]
Hola capehill

El 14-07-2020, escribiste:

> Any news?

TBH it worked fine last time a compiled/tested checkeys, but I get again SysReq instead of PrtScr ¿:-/

#version SOBJS:libSDL2.so file
libSDL2.so 0.12
#list check#?
checkkeys.o                   65448 ----rw-d Hoy       14:56:57
checkkeys                   4199995 ----rwed Hoy       14:56:59
checkkeys.c                    6370 ----rw-d 27-Abr-20 17:39:55
3 ficheros - 4171K bytes - 8348 bloques usados
#checkkeys 
INFO: Initial state: modifiers: (none)
INFO: Key pressed :  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key released:  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key pressed :  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key released:  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key pressed :  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key released:  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key pressed :  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
INFO: Key released:  scancode 154 = SysReq, keycode 0x4000009A = SysReq  modifiers: (none)
#


Will check it again, so I don't have mixed/old SDL2 headers/libs/...


BTW Can you (re)compile for me (for testing/comparing) static(aly) checkeys  test and send PM (jabierdlr@gmail.com) in case is my headers/lib structure/tree I have wrong.



Saludos
-- 
AOS4.1/SAM460ex/PPC460EX-1155MHZ/2048MB/RadeonRX550/SSD240GB/DVDRW  :-P

**Comment by capehill** [comment]
Please note that commit is only in the master branch, and was not a part of the 2.0.12 release.

So you have to build the master, or wait for the 2.0.13 test build.

**Comment by javierdlr** [comment]
Hola capehill

El 14-07-2020, escribiste:

> Please note that commit is only in the master branch, and was not a part
> of the 2.0.12 release.
>
> So you have to build the master, or wait for the 2.0.13 test build. 

Ok then, I tested latest 2.0.12 release/build. Will download 2.0.13 compile and see what happens.

THX


Saludos
-- 
AOS4.1/SAM460ex/PPC460EX-1155MHZ/2048MB/RadeonRX550/SSD240GB/DVDRW  :-P

**Comment by javierdlr** [comment]
Hola capehill

El 14-07-2020, escribiste:

> Please note that commit is only in the master branch, and was not a part
> of the 2.0.12 release.
>
> So you have to build the master, or wait for the 2.0.13 test build. 

Seems I need to wait to 2.0.13, 'cos trying to compile under OS4 I got some errors when compiling src/video/amigaos4/SDL_os4opengl.c, maybe I have old minigl headers.

my proto/minigl.h is:
*
**  $Id$
**  Includes Release 50.1
**
**  Prototype/inline/pragma header file combo
**
**  (C) Copyright 2003-2005 Amiga, Inc.
**      All Rights Reserved
*/

and mgl/minigl.h:
*
 * $Id: minigl.h 493 2015-08-03 16:58:26Z sbiro $
 *
 * $Date: 2015-08-04 04:58:26 +1300 (Tue, 04 Aug 2015) $
 * $Revision: 493 $
 *
 *(C) 1999 by Hyperion
 * All rights reserved
 *
 * This file is part of the MiniGL library project
 * See the file Licence.txt for more details
 *
 */


THX anyway.


Saludos
-- 
AOS4.1/SAM460ex/PPC460EX-1155MHZ/2048MB/RadeonRX550/SSD240GB/DVDRW  :-P

**Comment by capehill** [comment]
What kind of errors? Have you tried to install the latest available MiniGL from OS4Depot?

**Comment by javierdlr** [comment]
Hola capehill

El 19-07-2020, escribiste:

> What kind of errors? Have you tried to install the latest available
> MiniGL from OS4Depot?

Nopr, :-( using os4depot minigl includes, no problems :-)

and PrtScreen (checkkeys) key shows/works fine:
#make -f Makefile.amigaos4 
ppc-amigaos-gcc -gstabs -O2 -Wall -ISDK:Local/newlib/include/SDL2 -DHAVE_OPENGL   -c -o checkkeys.o checkkeys.c
ppc-amigaos-gcc -o checkkeys checkkeys.o -lSDL2 -athread=native
#checkkeys 
INFO: Initial state: modifiers: (none)
INFO: Key pressed :  scancode 70 = PrintScreen, keycode 0x40000046 = PrintScreen  modifiers: (none)
INFO: Key released:  scancode 70 = PrintScreen, keycode 0x40000046 = PrintScreen  modifiers: (none)
INFO: Key pressed :  scancode 70 = PrintScreen, keycode 0x40000046 = PrintScreen  modifiers: (none)
INFO: Key released:  scancode 70 = PrintScreen, keycode 0x40000046 = PrintScreen  modifiers: (none)
INFO: Key pressed :  scancode 71 = ScrollLock, keycode 0x40000047 = ScrollLock  modifiers: (none)
INFO: Key released:  scancode 71 = ScrollLock, keycode 0x40000047 = ScrollLock  modifiers: (none)
...


THX a sorry for all the hassle.





Saludos
-- 
AOS4.1/SAM460ex/PPC460EX-1155MHZ/2048MB/RadeonRX550/SSD240GB/DVDRW  :-P

**Comment by capehill** [comment]
Nice to hear it works. I guess this one can be closed then.
