### ISSUE TITLE
Some pixels on the right are cut off

### ISSUE THREAD

**Issue by afalkenhahn** [AmigaPorts/SDL_old#154]
I noticed that SDL2 for OS4 cuts off some pixels on the right. Check out this screenshot:

![test](https://user-images.githubusercontent.com/6772528/86141289-2abb6e80-baf2-11ea-8069-159ea1318c5a.png)

You can see that the pixels on the right are cut off. It is a little strange because the window size is correct (360x284 pixels) and the texture is the same size but still it somehow gets cropped. This seems to happen with all programs.

You can try the "Turrican2" example that comes with RebelSDL to see the issue but it's also visible with other RebelSDL examples.

**Comment by capehill** [comment]
Observations so far:
- SW renderer doesn't seem to be impacted
- Window size matters
- scalex has a scretched value "2.13" (when using 200%): dest. rect width 768 doesn't match window or bitmap width 720..

**Comment by capehill** [comment]
Root cause seems to be using BMA_Width instead of BMA_ActualWidth in the function that returns dimensions to the renderer core.

**Comment by capehill** [comment]
Please retest with https://github.com/AmigaPorts/SDL/releases/tag/v2.0.12-rc5-amigaos4

**Comment by afalkenhahn** [comment]
Thanks, the issue is gone with the latest build! Now the only issue left is white border on the bottom and the right, see here: https://github.com/AmigaPorts/SDL/issues/150

**Comment by capehill** [comment]
Merged into master.
