### ISSUE TITLE
[SDL1] Crash with GemRB 0.7.2 on AmigaOS 4

### ISSUE THREAD

**Issue by walkero-gr** [AmigaPorts/SDL_old#163]
Trying the GemRB 0.7.2 (http://os4depot.net/?function=showfile&file=game/strategy/gemrb.lha) on AmigaOS 4 with SDL 1.2 brings some serious crashes. 

Using the libSDL 1.2 (1.4 22/01/2018) crashes occur with graphics issue, which can be seen on the following screenshots:
https://drive.google.com/file/d/1xVBWGNJC9RglSsokWr8dfFfPwoza3wiI/view?usp=sharing
https://drive.google.com/file/d/1x_BT-Bqzic4q15WQI1bWeuAFPzEUF-tp/view?usp=sharing

I would like to mention here that the pointer is freezed, but not the keyboard, which I can use to switch screens. Also, the music keeps playing just fine, with no issues at all.

After that, I tried latest libSDL 1.2 (1.4 01/05/2020) and still crashes, but without the broken graphics, as shown at my screenshots mentioned above. I also tried the debug version and got the following messages from the serial https://os4coding.net/node/2426
The last line of this log repeats constantly.

I tried libSDL 1.2 (19/08/2012) and GemRB worked fine, with no problems at all.
My test machine is an AmigaOne X5000 with latest AmigaOS 4.1 FE beta version

**Comment by afxgroup** [comment]
it crash also on sam460ex while with original SDL included in the package it works

**Comment by capehill** [comment]
@walkero-gr  As mentioned on the forum, GemRB doesn't call SDL_Init which may cause some of the issues. Please try the attached version. Remove .zip prefix (it's an lha):

[SDL1_debug_test.lha.zip](https://github.com/AmigaPorts/SDL/files/5435306/SDL1_debug_test.lha.zip)

**Comment by samo79** [comment]
Not sure if related to the same problem reported by walkero but got a crash at startup while trying to start gemrb
I've installed the latest libsdl 1.2 posted above (installed in sobjs dir)

[Crashlog_GemRB_2020-11-05_08-19-17.txt](https://github.com/AmigaPorts/SDL/files/5498372/Crashlog_GemRB_2020-11-05_08-19-17.txt)

**Comment by capehill** [comment]
@samo79  I cannot see anything related to SDL in that stack trace.

**Comment by samo79** [comment]
Ok, this atleast confirm that it wasn't related, let's see if walkero still have the issue with that test version

**Comment by walkero-gr** [comment]
Hello guys. I am so sorry for this delayed reply. Today tested the debug version @capehill mentioned above and it worked fine with the GemRB on my system. Although I had some delays on pointer movement, but I guess that was because of the amount of information sent through serial port.

**Comment by capehill** [comment]
@walkero-gr try something like:

sashimi > RAM:serial.txt

**Comment by walkero-gr** [comment]
@capehill You need me to attach here the output? I don't need to use sashimi because I have a serial connection to an other machine. I can always grab it from there.

**Comment by capehill** [comment]
@walkero-gr  No thanks. You can try the trick if you want to be sure about serial slowdown, but I guess serial debug is the reason. So I will proceed with merge and maybe there will be a release candidate later on (this year?).

**Comment by capehill** [comment]
Closing with 1.2.16 RC2.
