### ISSUE TITLE
Add define for the function GLBlendModeHack

### ISSUE THREAD

**Issue by BeWorld2018** [AmigaPorts/SDL_old#185]
Hi

It's possible to put a define for the function  GLBlendModeHack
This function working for MorphOS

https://github.com/BSzili/SDL/commit/eee96d27c0b45dc1353ac6ac6c49827f43be8b1a

I also added your fix here : https://github.com/BSzili/SDL/commit/eee96d27c0b45dc1353ac6ac6c49827f43be8b1a#diff-4956a04b2a5178a1ab45e6567ebbd365a956893ddc64227a9f14d1ea211a634dR1231
I dont know if necessary for AmigaOS, but here working better....

Thanks

**Comment by capehill** [comment]
Hello,

1) Does MorphOS have glBlendFuncSeparate and glBlendEquation functions? If not, I think we could have the same fallback for OS4/MOS: if function pointers are NULL, then do "blend hack", otherwise use proper functions.

2) About enabling texturing: how this issue can be triggered? Please note that SDL folks fixed something earlier this year (BZ 4998).

**Comment by BeWorld2018** [comment]
hi,

1. no dont have  glBlendFuncSeparate and glBlendEquation functions here
2. dont know but if i dont enable, i have a white screen

But anywhay, i need to wait next release of MorphOS with better support of GL_BGRA.. until that BLEND doesnt working

thanks

**Comment by capehill** [comment]
2. can you reproduce white screen by using some SDL2 tests, like testsprite2 --renderer opengl?

I guess there is a possibility that issue is MorphOS-specific (differences between MiniGL and TinyGL or drivers).

**Comment by BeWorld2018** [comment]
MorphOS Team do that : tingl convertion GL_RGBA to GL_BGRA. : https://morph.zone/modules/newbb_plus/viewtopic.php?topic_id=12836&forum=12
Seem to be available on next release.

I have a beta version of it, and with this fix, i have 90% of game working with opengl renderer.
But now I have problem with BLEND mode, this is why i launch this discussion.
(PS: normaly MOS Team will check)

testsprite2 result :
![image](https://user-images.githubusercontent.com/36823759/99435816-f6b1e000-2910-11eb-8929-ac9a7bef303f.png)

with software
![image](https://user-images.githubusercontent.com/36823759/99435845-ffa2b180-2910-11eb-8c6d-4c232457f56b.png)

**Comment by BeWorld2018** [comment]
I close this issue.
