### ISSUE TITLE
Invalid SDL_TEXTINPUT events are sent on certain keyboard combos

### ISSUE THREAD

**Issue by ccawley2011** [AmigaPorts/SDL_old#190]
It looks like it's possible for SDL to send SDL_TEXTINPUT events where the `text` member is empty, which is what caused [this ScummVM bug](https://bugs.scummvm.org/ticket/12012). This was worked around in ScummVM in commit scummvm/scummvm@ade345b, but it may be a good idea to fix the issue here in case it affects other applications.

**Comment by capehill** [comment]
Thanks for the report.

It looks like backend was sending invalid single-byte sequences (from UTF-8 point of view) to the SDL core which then sent empty strings to the application. I have a workaround proposal and hopefully @raziel- would be able to test it:

http://capehill.kapsi.fi/scummvm/SDL2_textinput_workaround.lha

**Comment by raziel-** [comment]
@capehill 

Thank you very much for the quick response.

I'll do the testing as soon as I'm back home, though that will be next week earliest.

**Comment by raziel-** [comment]
@capehill
@ccawley2011

SDL2 workaround in place.
Compiling a ScummVM version BEFORE the ScummVM workaround was added yields no more assertions/crashes.
So it's fixed. :-)

Thank you very much

**Comment by capehill** [comment]
Thanks. I'm closing this with 2.0.14 RC2: https://github.com/AmigaPorts/SDL/releases/tag/v2.0.14-rc2-amigaos4
