### ISSUE TITLE
Add menu to window

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/SDL_old#191]
The idea was picked by the old PowerSDL from MorphOS, but now it was reimplemented by BeWorld even in the MorphOS port of SDL2

https://github.com/BSzili/SDL/commit/bf2c692d3bdc66daf487b48a81fbf134dcd76955

I wonder if it could be possible to integrate a similar functionality also in our SDL2 for AmigaOS4

**Comment by capehill** [comment]
Moved.
