### ISSUE TITLE
SDL1: Mouse pointer speed discrepancy between SDL1 and 2

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#193]
SDL 1.2.16 features a far slower mouse movement as it is present in SDL2.0.14.

The mouse speed in SDL2 is more or less the speed it is in Workbench while SDL1 seems to be like the "acceleration" was turned off.

Tested with SDL1 and 2 versions of ScummVM while in the launcher

**Comment by raziel-** [comment]
@capehill 

Should we keep this open?
SDL1 is pretty much EoL

**Comment by capehill** [comment]
Sorry I haven't investigated this. If you think this is relevant then please consider moving to to current issues tracker. For example, https://github.com/AmigaPorts/SDL-2.0/issues

**Comment by raziel-** [comment]
The mouse speed is slower in SDL1 compared to SDL2.

SDL1 is EoL so i'm closing this
