### ISSUE TITLE
Issues with certain video formats (SDL 1.2.16)

### ISSUE THREAD

**Issue by samo790** [AmigaPorts/SDL_old#197]
By working on an SDL/GL video outputs for MPlayer we found a problem with latest SDL1
Using the latest SDL 1.2.16 certain video formats start showing garbage on screen (in fullscreen)

This is the strange effect recordered on camera:
https://uploadnow.io/files/Tm6DkWz

By investigated a bit more we noted that the issue are not effecting every kind of video formats, for example with AVI files the graphical glitch are not visibile at all, while instead MPEG and MP4 files seems suffered of this problem!

As we reverted back to the latest SDL 1.2.15 everything gone, and all works as they should, so most probably we have a regression here

**Comment by capehill** [comment]
Sorry, but this is an old repo which will not be updated. For SDL1 issues, go https://github.com/AmigaPorts/SDL-1.2

(but don't your breath)

**Comment by samo790** [comment]
Ok, do i need to back-post the issue there or ... ?

Sorry, but this is an old repo which will not be updated. For SDL1 issues,
