### ISSUE TITLE
Native makefile

### ISSUE THREAD

**Issue by capehill** [AmigaPorts/SDL_old#24]
Native, simple, makefile would be nice to have.

Using configure + make has libtool-related (?) issue which prevents shared object building unless makefile is modified (remove -no-undefined).

Cmake works natively, but cmake as a tool is not very well supported on the native platform.

**Comment by MBeijer** [comment]
Is this related to SDL 1 or 2 or both?

**Comment by capehill** [comment]
SDL2, SDL1 has already one.

**Comment by kas1e** [comment]
@Bszili
Should't be also src/render/opengles2/ be in makefile as well ? Currently it builded by default inside of SDL2.
