### ISSUE TITLE
Implement native threads

### ISSUE THREAD

**Issue by capehill** [AmigaPorts/SDL_old#26]
Our port uses pthreads and it generally seems to work ok. There are still some issues:

1) configure + makefile refuses to build shared object, apparently this is related to libtool and -no-undefined parameter.

2) an attempt to use libSDL2.so from a Hollywood plugin crashes due to some pthread-related issue.

3) an attempt to build native sdl2.library crashes due to some pthread-related issue.

Having native threads would probably get rid of all these issues, or at least enable us to debug the crashes. As a reference, SDL1 uses native threads.

**Comment by BSzili** [comment]
This would be useful for a future an AROS and OS3.x port as well. I did look at the OS4 SDL 1.2 threading implementation, but it looks needlessly complicated compared to the other platforms. A native timer implementation will probably be necessary as well.

**Comment by capehill** [comment]
@BSzili 

I remove myself as an assignee since I'm not working at this thing currently. I agree about 1.2 complexity, any improvement on that area would be great.
