### ISSUE TITLE
Add a version tag

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/SDL_old#27]
It has been requested that .so would contain version information (and date).

Copied from Sourceforge bugtracker (Ticket 28)

https://sourceforge.net/p/sdl2-amigaos4/tickets/28/

**Comment by capehill** [comment]
This should be now easier to implement, thanks to the native makefile. It's still a little bit open what numbering should be in version string. SDL uses major.minor.patch. It was proposed earlier than AmigaOS version string could contain "minor.patch" because "major" (2) is assumed.

**Comment by BSzili** [comment]
I second minor.patch, as the major version number won't change for SDL2.

**Comment by samo79** [comment]
Mmm what's wrong with a "classic" Amiga like version ?

   Something like:

   SDL 2.0.9 (xx-xxx-2019)

   Or in case of SDL1:

   SDL 1.2.15 (xx-xxx-2019)

**Comment by BSzili** [comment]
Amiga version strings always had a version.revision numbering scheme:
http://openamiga.org/?function=viewpage&pageid=16
