### ISSUE TITLE
Add iconification support for SDL1, based on SDL2 iconification support

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#28]
Will be pretty helpfull if iconification support from SDL2 can be added the same way to SDL1, as it can make all our current SDL1 ports looks and be controlled much better.

thanks !

**Comment by MBeijer** [comment]
There's a big difference between SDL 1.2 and 2, so the API is quite different. It's possible that it is quite a task to add this.

**Comment by kas1e** [comment]
Thanks for answer, but i wrote bz after discussing with Capehill already. Was in hope he automaticaly assigned to, as well as he is main mantainer. Wasnt even aware that there is anyone else, sorry :)

**Comment by MBeijer** [comment]
Don't worry! We do both get notifications about these issues, but as stated before, I am more responsible for classic amiga.

**Comment by kas1e** [comment]
Probably we can close that issues as well, as seems iconification branch of SDL1 works as should. If something will going wrong, we always can reopen it
