### ISSUE TITLE
Add debug libraries to SDL1, as done for SDL2

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#29]
Currently on SDL2 we have 2 linker libraries : libSDL.a and libSDL_debug.a That very handy, as for testing purposes you just link against libSDL_debug.a , and for release ones you do link with libSDL.a.

Have the same being done for SDL1, will be very handy. So there will be no needs to enable/disable debug output all over the code of SDL all the time, and only swaping of linker libs will do the trick.

Thanks!

**Comment by MBeijer** [comment]
There are some debugging in place already in SDL1, you just need to compile it with the right parameters (afaik). Since @capehill is responsible for binary releases, I'll assign hime to the issue and we'll see if he will take the task. :)

**Comment by kas1e** [comment]
Thanks for answer, but i also add that issue after discussing it with Capehill, just so it not forgotten :) He already do it for os4 version of sdl2, and have the same be in repo for aos4 version of sdl1 (and so binary releases), will be just helpfull. Not that i do not know where current debug info left :)

That all about aos4 version of course, and i wasnt aware there is anyone else at all except him :)

**Comment by MBeijer** [comment]
I'm mainly responsible for AmigaOS3.x / SDL1.2, but I am also working on an SDL2 port for classic Amigas. :) The intention of this project is also to unify development of SDL for all Amiga platforms!

**Comment by capehill** [comment]
https://github.com/AmigaPorts/SDL/releases/tag/v1.2.15-rc1-amigaos4 has debug libraries.

Ideally makefile would be improved so that it could build all automatically, or when asked "make debug", for example.
