### ISSUE TITLE
OpenGL renderer content draw problem on window resize

### ISSUE THREAD

**Issue by raziel-** [AmigaPorts/SDL_old#35]
SDL2.0.8
AmigaOS4 - PPC - BE

If i resize a window in ScummVM with CTRL+LALT+(- or +) the window itself gets resized correctly (or so it seems) but the content of said window is drawn incorrectly (either squeezed horizontally, where the content is in the upper half or stretched horizontally where the content vanishes behind the bottom border.

Easy to check with a SDL2 build of ScummVM (no engines needed as the launche displays the problem just fine.

1) Start ScummVM
2) In "Options", choose "IOpenGL" as "GfxMode" and Apply/OK
3) In Window mode, press CTRL+LALT+"+"

Every resoltion change makes the contents go bonkers, using either "+" to enahnce or "-" to reduce the resolution.

**Comment by raziel-** [comment]
Confirmed fixed with minigl.lib from #34

**Comment by capehill** [comment]
Closing as a MiniGL issue.
