### ISSUE TITLE
[SDL1]: list of modes returned by SDL_ListModes() didn't sorted correctly.

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#51]
According to the https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdllistmodes.html, the list of screenmodes should be  sorted from largest to smallest (as it done on win32 and linux for example), while on amigaos4 realisation, we have in output something like this:

more_num: 0, w = 1920, h = 1200
more_num: 1, w = 1600, h = 1200
more_num: 2, w = 1920, h = 1080
more_num: 3, w = 1440, h = 900
more_num: 4, w = 1024, h = 768
more_num: 5, w = 1280, h = 720

While should be:

more_num: 0, w = 1920, h = 1200
more_num: 2, w = 1920, h = 1080
more_num: 1, w = 1600, h = 1200
more_num: 3, w = 1440, h = 900
more_num: 5, w = 1280, h = 720
more_num: 4, w = 1024, h = 768

**Comment by capehill** [comment]
Tested with testvidinfo, and seems to be better now.

**Comment by kas1e** [comment]
Yeah, confirmed ! Thanks !
