### ISSUE TITLE
[SDL1]: SDL_GetVideoSurface() return also SDL_PREALLOC flag, which, when  SDL_OPENGL | SDL_RESIZABLE requered make SDL1's os4video_SetVideoMode()  do not call resizing code.

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#52]
There is simple test case showing the problem:

```
#include <stdio.h> 
#include <SDL/SDL.h> 

int main() 
{ 
     const SDL_VideoInfo* info = NULL; 
     int flags = SDL_OPENGL | SDL_RESIZABLE; 
     static int vidmode_bpp=0; 
     SDL_Surface * screen; 

     SDL_Init( SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_AUDIO); 
     info = SDL_GetVideoInfo( ); 
     vidmode_bpp = info->vfmt->BitsPerPixel; 
     SDL_SetVideoMode( 640, 480, vidmode_bpp, flags ); 

     screen = SDL_GetVideoSurface(); 

     printf("flags in dec = %dn", flags); 
     printf("flags in hex = %xn", flags); 
     printf("flags_from_screen in dec = %dn", screen->flags); 
     printf("flags_from_screen in hex = %xn", screen->flags); 

     SDL_Quit(); 
}
```

The output for win32 and linux are:

>$ ./sdltest
flags in dec = 18
flags in hex = 12
flags_from_screen in dec = 18
flags_from_screen in hex = 12

The output for amigaos4 are:

> sdltest
flags in dec = 18
flags in hex = 12
flags_from_screen in dec = 16777234
flags_from_screen in hex = 1000012

Because of returned 1 at begining of byte (meaning SDL_PREALLOC), the compare code of the SDL1's os4video_SetVideoMode() didn't do  `Resizing window` code, and so, visually when we try to resize window by sizing gadget  nothing changes, because SDL1 think it is not `SDL_OPENGL | SDL_RESIZABLE`.

Probabaly, the way how it can be fixed, its adding to os4video_SetVideoMode() check on that SDL_PREALLOC, or, check why that flag returned , and if it possible to not return it.

**Comment by capehill** [comment]
Please try surface-prealloc branch, if possible.

**Comment by kas1e** [comment]
Yes, can confirm that resizine in window mode in the game which have use that kind of check start to works with surface-prealloc branch. Thanks ! :)
