### ISSUE TITLE
[SDL2]: iconification bug #1: missing iconify gadget after we switch from fullscreen to window mode via alt+enter / SDL_SetWindowFullscreen() 

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#53]
When you run sdl2 app in window mode it have iconification gadget all fine. But then, when you switch to fullscreen (via SDL_SetWindowFullscreen() ), and then back to the window via the same SDL_SetWindowFullscreen(), then iconify gadget disappear. Like code which re-create window forgot to add iconification gadget as it done when window firstly created.

Just running as default in fullscreen and then switch back to window cause same effect.

**Comment by capehill** [comment]
Fixed, thanks
