### ISSUE TITLE
[SDL2]: ogles2 : When window is destroyed, it seems to leave the OGLES2 context with a dangling window pointer.

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#55]
When i test swithcing between window and fullscreen modes in the OGLES2 application, found that once you switch via SDL_SetWindowFullscreen it crashes on the swapbuffer function in ogles2.library. So after discussing it on amigans.net we come to conclustion that when window is destroyed, it seems to leave the OGLES2 context with a dangling window pointer.

So, OGLES2 provide us with way to update context's window pointer:

```
struct TagItem setparams[] = 
{ 
        {OGLES2_CCT_WINDOW, (ULONG)data->syswin}, 
        {TAG_DONE, 0} 
}; 

aglSetParams2(setparams); 
```

So i just add it to the `OS4_GLES_SwapWindow()`, after `if (videodata->vsyncEnabled) {` , and before `aglSwapBuffers()`, like that:

```
           ...........

           if (videodata->vsyncEnabled) { 
                IGraphics->WaitTOF(); 
            } 

            struct TagItem setparams[] = 
            { 
                {OGLES2_CCT_WINDOW, (ULONG)data->syswin}, 
                {TAG_DONE, 0} 
            }; 

            aglSetParams2(setparams); 

            aglSwapBuffers();

            ............
```

And it did the trick, all works as expected.  Not sure through if it right place to call it there, or if it should be called always like this (maybe some "if non-valid window-check" is need it for or something), but seems it fix issue anyway.

**Comment by capehill** [comment]
Thanks. I think I will apply this with minor modifications. Basically this would be only necessary if window pointer changed, but to track pointer change we would need add extra variable in context struct. So let's start with this and improve workaround if there will be any performance issues or such.

**Comment by kas1e** [comment]
Yeah, because probably as it now, it will slow things down a bit (a very little, but still), as it will call one more function in the such important speed related part as swapping of buffers. From other side, if we will add there some "if" check , that also will take time (maybe the same as just calling of function) ?

**Comment by capehill** [comment]
If function call only sets a pointer inside OGLES2, it's probably blazing fast (in microsecond category). If it does lots of other house-keeping things, then it might be slow. If it takes more than 1 millisecond then we need to improve it...

**Comment by kas1e** [comment]
I will ask Daniel about

**Comment by kas1e** [comment]
So, Daniel says that it wrong to add it there, as it wrong by semantic as minimum, as we should't count of how fast or slow aglSetParam is perfoms. We should't call it all the time when swapbuffer called, we should it call _only_ when we toggle bettwen fullscreen and window.

Sure we can count on how fast or slow it called, but its still wrong to have it inside of swapbuffer() function (as we both expect from begining, but for tests it was ok).

And as we both assume before, the right place to call that functions will be inside of the SDL_ToggeFullscreen() function.  And there add something like that:

```
#ifdef OGLES2
if(window-pointer-changed) { aglSetParam} else {}
#endif
```
But for sure it should go from swapbuffer function to ToggleFullScreen one, as it one where we have problems.

**Comment by capehill** [comment]
Yes, I know that it doesn't belong to SwapBuffers. But this is not completely trivial issue because of SDL2 supports at the same time MiniGL and OGLES2. So I need to add some backend function which gets called from SDL_os4window. SDL_os4window code doesn't know whether there is a MiniGL context or an OGLES2 context: it has only some function pointers. So for clean implementation there has to be something like OS4_GL_UpdateWindowPointer() which is a NOP for MiniGL and does something for OGLES2.

**Comment by capehill** [comment]
Tested by kas1e, should be OK now -> closing.
