### ISSUE TITLE
[SDL2]: minor/trivial issue in the test/testgles2.c example

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#56]
At top of the test/testgles2.c example we have currently that:

```
#if defined(__IPHONEOS__) || defined(__ANDROID__) || defined(__EMSCRIPTEN__) || defined(__NACL__) \
    || defined(__WINDOWS__)
#define HAVE_OPENGLES2
#endif  

#ifdef HAVE_OPENGLES2
... all the code of the testgles2.c is here ...
#endif
````

So, there is missing amigaos4 ifdef, as without no code compiles as we didn't go through `#ifdef HAVE_OPENGLES2` part, so just adding at end of that line `|| defined(__amigaos4__)` will fix it.

**Comment by capehill** [comment]
I can't reproduce this issue. When doing:

make testgles2

there is -DHAVE_OPENGLES2 on command line. Did you configure test dir? How is your command line?

**Comment by kas1e** [comment]
Oh, then if you use make testgles2 and it provide -DHAVE_OPENGLES2 it of course works. I just compile it manually, without "make", just pure "gcc testgles2.c blalblab". And code anyway looks like it want amigaos4 ifdef to set opengles2 define, maybe worth add as well anyway as all other oses in that ifdef , so anyone who will try to compile it manually, will have it works the same as if it will be compiled via make ?

**Comment by capehill** [comment]
Adding define HAVE_OPENGLES2 in source would only give redefinition warning so I am not going to add it currently

**Comment by kas1e** [comment]
Ok, no problems. If all expected to be like this then we can close that one as well

**Comment by capehill** [comment]
I have always ran configure for test dir and either "make" or "make testxyz". It is fairly convenient, for me at least.
