### ISSUE TITLE
[SDL1/2]: Made change in iconification's code, so X/Y values of icon after snaphooting didn't take in account when iconify.

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#75]
As we discuss previously on forum, currently when we snapshot the icon in the workbench window and X or Y start to be big enough, then when we do iconification instead of putting icon in the next free slot on workbench screen (as expected from pure iconificatino) , it start to place icon on the workbench screen in different places (depend on how bug X/Y of snapshoted icon).

Solution was give by Trixie:

If you use a program icon for iconification purposes, you should set the do_CurrentX and do_CurrentY fields in the icon's DiskObject structure to the value of NO_ICON_POSITION. Unless you call PutDiskObject() with the modified DiskObject as parameter, no change will be made to the actual icon on disk, and the icon's original X/Y coordinates will be preserved.

**Comment by kas1e** [comment]
@Capehill
I just OS4_GetDiskObject() in the SDL_os4window.c as Trixie suggest and it works indeed. Just in case i set it to fallback one as well (to avoid problems when default on snapshoted somehow different too). 

There is:

```
static struct DiskObject* OS4_GetDiskObject(_THIS)
{
    SDL_VideoData *videodata = (SDL_VideoData *) _this->driverdata;
    struct DiskObject *diskObject = NULL;

    if (videodata->appName) {
        BPTR oldDir = IDOS->SetCurrentDir(IDOS->GetProgramDir());
        diskObject = IIcon->GetDiskObject(videodata->appName);
        diskObject->do_CurrentX = NO_ICON_POSITION;
        diskObject->do_CurrentY = NO_ICON_POSITION;
        IDOS->SetCurrentDir(oldDir);
    }

    if (!diskObject) {
        CONST_STRPTR fallbackIconName = "ENVARC:Sys/def_window";
        dprintf("Falling back to '%s'\n", fallbackIconName);
        diskObject = IIcon->GetDiskObjectNew(fallbackIconName);
        diskObject->do_CurrentX = NO_ICON_POSITION;
        diskObject->do_CurrentY = NO_ICON_POSITION;

    }

    return diskObject;
}
```

**Comment by capehill** [comment]
Should be fixed, please confirm (but no need to hurry).

**Comment by kas1e** [comment]
Yes, tested, everything fine, thanks !
